control 'SV-233181' do
 title 'All audit records must use UTC or GMT time stamps.'
 desc 'The container platform and its components must
 generate audit records using either Coordinated Universal Time (UTC) or Greenwich
 Mean Time (GMT) time stamps or local time that offset from UTC. All the components
 must use the same standard so that the events can be tied together to understand
 what took place within the overall container platform. Time stamps generated by the
 container platform and its components must include date and
 time.'
 desc 'check', 'Review the container platform documentation and configuration files
 to determine if time stamps for log records can be mapped to UTC or GMT or local
 time that offsets from UTC. If the time stamp cannot be mapped to UTC or GMT,
 this is a finding.'
 desc 'fix', 'Configure the container platform to use UTC or GMT
 or local time that offset from UTC based time stamps for log records.'
 impact 0.5
 tag check_id: 'C-36117r601030_chk'
 tag severity: 'medium'
 tag gid: 'V-233181'
 tag rid: 'SV-233181r961443_rule'
 tag stig_id: 'SRG-APP-000374-CTR-000865'
 tag gtitle: 'SRG-APP-000374'
 tag fix_id: 'F-36085r601031_fix'
 tag 'documentable'
 tag cci: ['CCI-001890']
 tag nist: ['AU-8 b']
 tag implementation_status: 'implemented'

 # Durable, tamper-evident audit-record generation via account CloudTrail (cross-validates
 # cis-aws-foundations). CloudTrail's record schema carries event type/time/source/user.
 ok = audit_trail_compliant?
 impact 0.5
 describe 'CloudTrail audit-record generation (multi-region + log-file-validation + S3)' do
 subject { ok }
 it { is_expected.to be true }
 end
end
