control 'SV-233267' do
 title 'The container platform runtime must generate audit records when
 successful/unsuccessful attempts to access objects occur.'
 desc 'Container platform runtime objects are defined as
 configuration files, code, etc. This provides the ability to configure resources and
 software parameters prior to image execution from the container platform registry.
 An unauthorized user with malicious intent could modify existing objects causing
 vulnerabilities or attacks. It would be difficult to establish, correlate, and
 investigate events relating to an incident or identify those responsible without
 audit record generation. Without audit record generation, unauthorized users can
 access objects unknowingly for malicious intent creating vulnerabilities within the
 container
 platform.'
 desc 'check', 'Review the container platform configuration to verify that the
 runtime generates audit records on successful/unsuccessful access to objects. If
 audit records are not generated by the runtime when objects are
 successfully/unsuccessfully accessed, this is a finding.'
 desc 'fix', 'Configure the container platform runtime to
 generate audit records on successful/unsuccessful access to objects.'
 impact 0.5
 tag check_id: 'C-36203r601884_chk'
 tag severity: 'medium'
 tag severity_source: 'DISA SRG'
 tag gid: 'V-233267'
 tag rid: 'SV-233267r961836_rule'
 tag stig_id: 'SRG-APP-000507-CTR-001295'
 tag gtitle: 'SRG-APP-000507'
 tag fix_id: 'F-36171r601289_fix'
 tag 'documentable'
 tag cci: ['CCI-000172']
 tag nist: ['AU-12 c']
 tag nist_r4: ['AU-12 c']
 tag implementation_status: 'inherited'
 tag inherited_from: 'aws-shared-responsibility'

 # AWS-managed container-platform layer (runtime/host/control-plane/crypto-module/audit-
 # infra). Evidence = the leveraged the cloud-provider authorization manifest; Skip (not a
 # vacuous pass) until the consumer configures leveraged_evidence_base/inherited_evidence_uri.
 ev = input('inherited_evidence_uri', value: '')
 ev = attestation_uri(:leveraged, 'aws-container-platform-authorization', ext: 'json') if ev.to_s.empty?
 max_age = input('leveraged_evidence_max_age_days', value: 365)
 impact 0.5
 if ev.to_s.empty?
 describe 'AWS-inherited authorization evidence' do
 skip 'inherited-from-aws: AWS-managed layer; set leveraged_evidence_base / inherited_evidence_uri to the cloud-provider authorization manifest, or supply a SAF attestation.'
 end
 else
 doc = document_attestation(ev, max_age_days: max_age)
 describe "AWS authorization evidence (#{ev})" do
 it('exists') { expect(doc.exists?).to eq(true) }
 it('current') { expect(doc.current?(max_age)).to eq(true) }
 end
 end
end
