control 'SV-233182' do
  title 'The container platform must record time stamps for audit records that meet a
                granularity of one second for a minimum degree of precision.'
  desc 'To properly investigate an event, it is important to
                have enough granularity within the time stamps to determine the chronological order
                of the audited events. Without this granularity, events may be interpreted out of
                proper sequence, thus hobbling the investigation or causing the investigation to
                come to inaccurate conclusions. Time stamps generated by the container platform
                include date and time. Granularity of time measurements refers to the degree of
                synchronization between information system clocks and reference
                clocks.'
  desc 'check', 'Review the container platform documentation and configuration files
                    to determine if time stamps for log records meet a granularity of one second. If
                    the time stamp cannot generate to a one-second granularity, this is a finding.'
  desc 'fix', 'Configure the container platform to use time stamps
                for log records that can meet a granularity of one second.'
  impact 0.5
  tag check_id: 'C-36118r601033_chk'
  tag severity: 'medium'
  tag gid: 'V-233182'
  tag rid: 'SV-233182r961446_rule'
  tag stig_id: 'SRG-APP-000375-CTR-000870'
  tag gtitle: 'SRG-APP-000375'
  tag fix_id: 'F-36086r601034_fix'
  tag 'documentable'
  tag cci: ['CCI-001889']
  tag nist: ['AU-8 b']
  tag implementation_status: 'implemented'

  # Durable, tamper-evident audit-record generation via account CloudTrail (cross-validates
  # cis-aws-foundations). CloudTrail's record schema carries event type/time/source/user.
  ok = audit_trail_compliant?
  impact 0.5
  describe 'CloudTrail audit-record generation (multi-region + log-file-validation + S3)' do
    subject { ok }
    it { is_expected.to be true }
  end
end
